 CREATE TABLE "DISPATCHER_LOG_APP" 
   (	"TIME_STAMP" DATE, 
	"FUNCTION_NAME" VARCHAR2(100 BYTE), 
	"MESSAGE_BODY" VARCHAR2(1000 BYTE), 
	"INSTANCE_NAME" VARCHAR2(100 BYTE), 
	"PROCESS_ID" VARCHAR2(50 BYTE)
   );

   CREATE TABLE "DISPATCHER_FILE_LOG" 
   (	"TIME_STAMP" DATE, 
	"FILE_NAME" VARCHAR2(200 BYTE), 
	"FILE_PATH" VARCHAR2(50 BYTE), 
	"REMOTE_FTP" VARCHAR2(100 BYTE), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"DOC_SIZE_BYTES" NUMBER(*,0), 
	"INSTANCE_NAME" VARCHAR2(100 BYTE), 
	"WORKER_ID" VARCHAR2(50 BYTE), 
	"TRANSFER_ID" VARCHAR2(50 BYTE), 
	"PROCESS_ID" VARCHAR2(50 BYTE)
   );